# Generated by Django 4.1.2 on 2022-10-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_remove_user_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='hotel name')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='hotel address')),
            ],
        ),
    ]
