# Generated by Django 4.1.2 on 2022-10-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_alter_room_hotel_reservation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('hotel', 'room', 'year', 'month', 'day'), name='unique_reservation'),
        ),
    ]
